id: P982B6E07
initial_creation_type: input
source_metadata:
  title: Gatön Ngawang Lekpa Series
  language: en
  description: 'Texts by and about the Sakya lama Gatön Ngawang Lekpa (sga ston ngag
    dbang legs pa, 1867–1941) of Tharlam Monastery, one of the foremost Lamdré (lam
    ’bras) teachers of recent times:'
  volume:
    e6c512de81f54b5daa575a2ade38c394:
      title: 'Ocean of Offering Clouds: A Light Offering Prayer'
      parent: Aspiration Prayers
    661be8c39f474204aa83a5b3817f86a0:
      title: 'The Heart of the Mahāyāna Path: A Bodhisattva’s Prayer of Aspiration'
      parent: Aspiration Prayers
    e924d41b93864bf7ba8a149bc5147c14:
      title: Supplement to the Lineage Prayer for the Lamdré Instructions Composed
        by Tsarchen
      parent: Lineage Prayers
    aadbb698374d4589af7fbf52f90a29a1:
      title: Aspiration for the Long Life of Dezhung Rinpoche (Jampa Kunga Tenpé Nyima)
      parent: Long Life Prayers
    5654600844ab4ebbb4d83ddb79ad4801:
      title: Prayer for the Long Life of Jamyang Khyentse Chökyi Lodrö
      parent: Long Life Prayers
    ff0387e10a114c3eb9a53fef6547cd2f:
      title: Prayer for the Long Life of Khyenrab Chökyi Özer
      parent: Long Life Prayers
    cb43ec7c0afd42e09d60c027ced7859e:
      title: 'Cloud Banks of Blessings: Praise and Prayer to the Vajradhara Ngawang
        Lekpa'
      parent: Praise
    34854cee18b64c12ad4fa308d9682201:
      title: Praise of Kunga Yeshe, Great Being and Master of Extensive Scriptural
        Traditions
      parent: Praise
created_at: '2022-02-28T23:22:34.049904'
last_modified_at: '2022-02-28T23:22:34.049910'
